Added gtc regression test for FVM nabla operator (gtscript -> generated code) (#54)
* Allow injection of static code blocks at the beginning of the generated code in UsidCodeGenerator

* Remove check in `UsidCodeGenerator` for conformance with sid concept as it triggers a compilation error in nvcc (workaround with templated function call instead of decltype possible, but withdrawn)

* Fix hardcoded name for temporary field in UsidCodeGenerator

* Added gtc regression test for FVM nabla operator (gtscript -> generated code)
 Note: driver code borrowed from cpputils regression tests via symlink for now

* Fix cmake not rebuilding on changes in cpputils and gtc regression tests

* Update src/gtc/unstructured/usid_codegen.py

Co-authored-by: Hannes Vogt <hannes@havogt.de>

* Update src/gtc/unstructured/usid_codegen.py

Co-authored-by: Hannes Vogt <hannes@havogt.de>

* Fix `ModuleNotFoundError: No module named 'eve'` in CI

* Added __init__.py to gt_frontent

* Remove obsolete hash_path in gtc regression tests cmake

* Revert "Fix `ModuleNotFoundError: No module named 'eve'` in CI"

This reverts commit cd7531d7357f3e7e47e067ed427de87075f49552.

* CI: pip install eve (#57)

Co-authored-by: Hannes Vogt <hannes@havogt.de>