GTScript unstructured prototype frontend (#52)
* Code cleanup

* GTC regression test temporary fields

* Code cleanup

* Code cleanup

* Enable stencil definition inside others functions

* Add additional stencils for the code generation unit tests

* Code cleanup

* Added cell to cell reduction example in preperation of GTIR extensions (this example is not meaningful at this point)

* GT4PyAst to GTIR working (rest unfinished and chaotic)

* fix minor bugs

* Some cleanup

* Allow sparse fields

* FVM Nabla stencil code generation working (c++ code not tested yet)
- Improved code quality
- Added sparse and temporary fields functionality to the prototype frontend
- Python ast templates are now seperate from the gtscript node definition
- Improved node canonicalization

* Renamed GT4PyAst into GTScriptAst
Code cleanup

* Moved unstructured prototype frontend examples to examples folder

* Tests and fixes (default captures) for ast_node_matcher

* Added file headers

* Unstructured cpp regression tests now use the prototype frontend instead of creating the IR manually
Minor fixes & cleanup

* Allow subscript in assignment

* Added shell commands for building atlas packages to cpputil README

* Removed accidentally commited (empty) files

* Removed cell_cell_reduction example

* Code format

* Added typing_inspect to known_third_party in setup.cfg

* Code cleanup

* Allow equality comparison of gtscript BuiltInTypes

* Improved error message

* Fix gtc cpp regression tests not rebuilding if python source changes

* Workaround for float constants being converted as integers in gtscript ast parsing

* Fix in gtscript NodeCanonicalizer, where `edges` call were converted into `neighbor(..., Vertex)` calls

* Workaround in gtscript symbol table to allow decleration of the same location symbol multiple times

* Code cleanup

* Fixed version requirement for typing_inspect in setup.cfg

* Extended documentation & code cleanup

* Extended documentation & code cleanup

* Update examples/unstructured/frontend.py

Co-authored-by: Rico Haeuselmann <r.haeuselmann@gmx.ch>

* Cleanup in src/gt_frontend/ast_node_matcher.py

Co-authored-by: Rico Haeuselmann <r.haeuselmann@gmx.ch>

* Added gtc regression test for FVM nabla operator (gtscript -> generated code) (#54)

* Allow injection of static code blocks at the beginning of the generated code in UsidCodeGenerator

* Remove check in `UsidCodeGenerator` for conformance with sid concept as it triggers a compilation error in nvcc (workaround with templated function call instead of decltype possible, but withdrawn)

* Fix hardcoded name for temporary field in UsidCodeGenerator

* Added gtc regression test for FVM nabla operator (gtscript -> generated code)
 Note: driver code borrowed from cpputils regression tests via symlink for now

* Fix cmake not rebuilding on changes in cpputils and gtc regression tests

* Update src/gtc/unstructured/usid_codegen.py

Co-authored-by: Hannes Vogt <hannes@havogt.de>

* Update src/gtc/unstructured/usid_codegen.py

Co-authored-by: Hannes Vogt <hannes@havogt.de>

* Fix `ModuleNotFoundError: No module named 'eve'` in CI

* Added __init__.py to gt_frontent

* Remove obsolete hash_path in gtc regression tests cmake

* Revert "Fix `ModuleNotFoundError: No module named 'eve'` in CI"

This reverts commit cd7531d7357f3e7e47e067ed427de87075f49552.

* CI: pip install eve (#57)

Co-authored-by: Hannes Vogt <hannes@havogt.de>

* Update src/gt_frontend/py_to_gtscript.py

Co-authored-by: Rico Haeuselmann <r.haeuselmann@gmx.ch>

* Comment out __metadata__ and select in BaseNode as they are unused right now and lead to errors with mypy

* Fix errors reported by mypy

* Reformat

* Fix flake8 errors

* Add code generation unit tests

* Distinguish between optional fields and fields with None value in ast_node_matcher

* Simplified ast_node_matcher again

Reformat

* Minor fix

* Addressed code quality remarks

* Reformat

* Update src/gt_frontend/py_to_gtscript.py

Co-authored-by: Enrique G. Paredes <18477+egparedes@users.noreply.github.com>

* Update src/gt_frontend/py_to_gtscript.py

Co-authored-by: Enrique G. Paredes <18477+egparedes@users.noreply.github.com>

* Update src/gt_frontend/py_to_gtscript.py

Co-authored-by: Enrique G. Paredes <18477+egparedes@users.noreply.github.com>

* Update src/gt_frontend/py_to_gtscript.py

Co-authored-by: Enrique G. Paredes <18477+egparedes@users.noreply.github.com>

* Addressed code quality remarks (instance attribute in __init__, f-strings, docstrings should end in period, capitalization, todo comment format)

* Reformat & Minor fix

* Addressed code quality remarks

* Reformat

Co-authored-by: Hannes Vogt <hannes@havogt.de>
Co-authored-by: Rico Haeuselmann <r.haeuselmann@gmx.ch>
Co-authored-by: Enrique G. Paredes <18477+egparedes@users.noreply.github.com>